### ISSUE TITLE
aeson bounds on hackage

### ISSUE THREAD

**Issue by mniip** [haskellari/postgresql-simple#162]
`postgresql-simple` versions `>=0.5.0.0 && <=0.5.4.0` on hackage have no upper bounds for `aeson` and fail to compile with `aeson >=2.2`:
```
src/Database/PostgreSQL/Simple/FromField.hs:120:1: error:
    Could not find module ‘Data.Aeson.Parser’
    Use -v to see a list of the files searched for.
    |
120 | import qualified Data.Aeson.Parser as JSON (value')
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Could you please make hackage revisions to exclude these configurations?

**Comment by phadej** [comment]
This configuration can occur only with GHC-8.4 or older, I'm not sure I have it on any machine anymore to test the revision properly.
